# -*- coding: utf-8 -*-
"""explain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jv09dUSnrU6EWVxJrwDpQxQIyNB0tlUq
"""

pip install numpy scikit-learn lime

import lime
from lime.lime_text import LimeTextExplainer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
import random

# Example sentences with labels
texts = [
    "I experienced chest pain and fatigue.",
    "The patient complained of shortness of breath and dizziness.",
    "Wheezing and coughing were observed in the patient.",
    "The patient has frequent urination changes and back pain.",
    "Chest tightness and fatigue were reported by the patient.",
    "Swelling and shortness of breath were evident in the patient.",
    "The patient presented with dizziness and back pain.",
    "Urination changes and wheezing were noted in the patient.",
    "I felt chest pain and had frequent urination changes.",
    "The patient had swelling and reported chest tightness.",
    "Shortness of breath and coughing were observed.",
    "The patient complained of fatigue and dizziness."
]

labels = [
    "heart", "heart", "asthma", "kidney",
    "heart", "kidney", "kidney", "asthma",
    "heart", "kidney", "asthma", "heart"
]



tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(texts)


naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X, labels)


def predict_proba(texts):
    X = tfidf_vectorizer.transform(texts)
    return naive_bayes_classifier.predict_proba(X)


explainer = LimeTextExplainer(class_names=["heart", "kidney", "asthma"])


prediction_to_explain = texts[0]
explanation = explainer.explain_instance(prediction_to_explain, predict_proba)


explanation.show_in_notebook()